### PR TITLE
Distinguish float type formatting from double

### LINKED ISSUE #1353: Cannot override float processing
Tried to override format for standard types according to documentation:

`
using arg_formatter = fmt::arg_formatter<fmt::back_insert_range<fmt::internal::buffer>>;

class na_arg_formatter : public arg_formatter {
public:
	na_arg_formatter(fmt::format_context &ctx, fmt::format_specs *spec = nullptr)
		: arg_formatter(ctx, spec),
		m_na_formatter(ctx)
	{}

	using arg_formatter::operator();

	auto operator()(double value) {
		if (IsNA(value))
			return m_na_formatter("NA");
		return arg_formatter::operator()(value);
	}

	auto operator()(float value) {
		if (IsNA(value))
			return m_na_formatter("NA");
		return arg_formatter::operator()(value);
	}

	auto operator()(unsigned value) {
		if (IsNA(value))
			return m_na_formatter("NA");
		return arg_formatter::operator()(value);
	}

	auto operator()(int value) {
		if (IsNA(value))
			return m_na_formatter("NA");
		return arg_formatter::operator()(value);
	}

private:
	arg_formatter m_na_formatter;
};

inline std::string na_vformat(fmt::string_view format_str, fmt::format_args args) {
	fmt::memory_buffer buffer;
	// Pass custom argument formatter as a template arg to vformat_to.
	fmt::vformat_to<na_arg_formatter>(buffer, format_str, args);
	return fmt::to_string(buffer);
}

template <typename ...Args>
inline std::string na_format(
	fmt::string_view format_str, const Args &... args) {
	return na_vformat(format_str, fmt::make_format_args(args...));
}
`

Float overloading is not working.
Double case is chosen.
`
na_format("{}", 4.f);
`

### PR DESCRIPTION
**Pull request by orivej**
This fixes #1353 and is the first half of the fix for #1336.

I suggest reviewing commits one by one.

### CODE REVIEW

File: include/fmt/format-inl.h [hunk 1]
```diff
@@ -980,6 +980,13 @@ FMT_API bool grisu_format(Double value, buffer<char>& buf, int precision,
   return true;
 }
 
+template <>
+char* sprintf_format<float>(float value, internal::buffer<char>& buf,
+                            sprintf_specs specs) {
+  // printf does not have a float format modifier, it only supports double.
+  return sprintf_format(double(value), buf, specs);
```
Comment (vitaut) [inline include/fmt/format-inl.h]: I suggest replacing this with 
```
return sprintf_format<double>(value, buf, specs);
```
to avoid cast.

**Comment by vitaut** [comment]
Merged, thanks!
