### PR TITLE
Fix error: cannot use 'try' with exceptions disabled in Win LLVM Clang

### LINKED ISSUE #4207: fmt/include\fmt/format-inl.h:1417:3: error: cannot use 'try' with exceptions disabled
Getting this error while compiling with LLVM clang++.exe on Windows, the exceptions are disabled `-fno-exceptions` and `-fms-compatibility` is not used: 
```
fmt/include\fmt/format-inl.h:1417:3: error: cannot use 'try' with exceptions disabled
 1417 |   FMT_TRY {
      |   ^
fmt/include\fmt\base.h:175:19: note: expanded from macro 'FMT_TRY'
  175 | #  define FMT_TRY try
      |  
```
Looks like relevant to #70 that does not seem to be properly/completely fixed.
The {fmt} version is [11.0.2](https://github.com/fmtlib/fmt/releases/tag/11.0.2).

### PR DESCRIPTION
**Pull request by sergio-nsk**
Fixes #4207.

LLVM Clang on Windows does not define `__GNUC__`. The preprocessor falls to `#elif FMT_MSC_VERSION && !_HAS_EXCEPTIONS` with `_HAS_EXCEPTIONS 1` defined in vcruntime.h:104.

### CODE REVIEW

**Comment by sergio-nsk** [comment]
Other GCC related macros missing LLVM Clang on Windows:
```diff
#define __GCC_ASM_FLAG_OUTPUTS__ 1
< #define __GCC_ATOMIC_BOOL_LOCK_FREE 2
< #define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
< #define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
< #define __GCC_ATOMIC_CHAR_LOCK_FREE 2
< #define __GCC_ATOMIC_INT_LOCK_FREE 2
< #define __GCC_ATOMIC_LLONG_LOCK_FREE 2
< #define __GCC_ATOMIC_LONG_LOCK_FREE 2
< #define __GCC_ATOMIC_POINTER_LOCK_FREE 2
< #define __GCC_ATOMIC_SHORT_LOCK_FREE 2
< #define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
< #define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
  #define __GCC_CONSTRUCTIVE_SIZE 64
  #define __GCC_DESTRUCTIVE_SIZE 64
< #define __GCC_HAVE_DWARF2_CFI_ASM 1
  #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
  #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
  #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
  #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
< #define __GLIBCXX_BITSIZE_INT_N_0 128
< #define __GLIBCXX_TYPE_INT_N_0 __int128
< #define __GNUC_GNU_INLINE__ 1
< #define __GNUC_MINOR__ 2
< #define __GNUC_PATCHLEVEL__ 1
< #define __GNUC__ 4
< #define __GNUG__ 4
< #define __GXX_ABI_VERSION 1002
< #define __GXX_EXPERIMENTAL_CXX0X__ 1
< #define __GXX_RTTI 1
< #define __GXX_WEAK__ 1
#define __INT16_C_SUFFIX__
```

**Comment by mwinterb** [comment]
clang-cl seems to [define](https://github.com/llvm/llvm-project/blob/20bda93e438c63fb68a8130b7f88090c558e99b7/clang/lib/Basic/Targets/OSTargets.cpp#L138-L144) `_CPPUNWIND`, which is the define that Microsoft lists in their predefined macros documentation.

**Comment by sergio-nsk** [comment]
@mwinterb You are right, `_CPPUNWIND` and `__cpp_exceptions` instead of `_HAS_EXCEPTIONS` are defined. Which one to use in this change?

**Comment by vitaut** [comment]
Please apply clang-format.

File: include/fmt/base.h [hunk 1]
```diff
@@ -146,6 +146,8 @@
 // Use the provided definition.
 #elif defined(__GNUC__) && !defined(__EXCEPTIONS)
 #  define FMT_USE_EXCEPTIONS 0
+#elif defined(__clang__) && (!defined(__cpp_exceptions) || __cpp_exceptions < 199711L)
```
Comment (vitaut) [inline include/fmt/base.h:149]: I wonder why they check against 199711L?

Comment (sergio-nsk) [reply include/fmt/base.h:149]: IDK. As I mentioned, this is how Clang does that C++ exceptions check.

Comment (vitaut) [reply include/fmt/base.h]: I suggest removing the `__cpp_exceptions < 199711L` part then if it works in your environment.

Comment (sergio-nsk) [reply include/fmt/base.h]: Yes, it works.
