### PR TITLE
Fix a conversion warning with Clang10 on Windows

### LINKED ISSUE #1747: -Wsign-conversion warning with Clang10 on Windows
include\fmt/format.h(560,71): error: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long long') to 'stdext::checked_array_iterator<char *>::difference_type' (aka 'long long') [-Werror,-Wsign-conversion]
  std::uninitialized_copy(begin, end, make_checked(ptr_, capacity_) + size_);

### PR DESCRIPTION
**Pull request by 0x8000-0000**
Fixes #1747

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

File: include/fmt/format.h [hunk 1]
```diff
@@ -566,7 +566,7 @@ template <typename U>
 void buffer<T>::append(const U* begin, const U* end) {
   size_t new_size = size_ + to_unsigned(end - begin);
   reserve(new_size);
-  std::uninitialized_copy(begin, end, make_checked(ptr_, capacity_) + size_);
+  std::uninitialized_copy(begin, end, make_checked(ptr_ + size_, capacity_));
```
Comment (vitaut) [inline include/fmt/format.h:569]: Thanks for the PR. I think you also need to subtract `size_` from `capacity_`.

Comment (0x8000-0000) [reply include/fmt/format.h:569]: Will do, but why do all the test pass? :)

Comment (vitaut) [reply include/fmt/format.h]: Because we don't write over capacity. The whole checked iterator machinery in MSVC is completely useless and is here mostly to avoid warnings but let's provide correct bounds anyway.

**Comment by vitaut** [comment]
Thank you!
