### PR TITLE
Also allow compiled format for clang >= 12

### LINKED ISSUE #4000: Failed to detect trunk clang to support pre-compiled format
This one does not compile: https://godbolt.org/z/x315Y9q8Y

However, once we manually define `FMT_USE_NONTYPE_TEMPLATE_ARGS`, it does compile: https://godbolt.org/z/nf1YPfMvG

### PR DESCRIPTION
**Pull request by yujincheng08**
Fix #4000

### CODE REVIEW

File: include/fmt/base.h [hunk 1]
```diff
@@ -145,6 +145,10 @@ import std;
 #elif defined(__cpp_nontype_template_args) && \
     __cpp_nontype_template_args >= 201911L
 #  define FMT_USE_NONTYPE_TEMPLATE_ARGS 1
+#elif defined(__clang_major__) && __clang_major__ >= 12 && \
+    __cplusplus >= 202002L
```
Comment (vitaut) [inline include/fmt/base.h:149]: Let's simplify this check to `FMT_CLANG_VERSION >= 1200 && __cplusplus >= 202002L`.

**Review by vitaut — CHANGES_REQUESTED** [review]

File: include/fmt/base.h (hunk 1 above)
Comment (yujincheng08) [reply include/fmt/base.h]: Done

**Review by vitaut — APPROVED** [review]

**Comment by vitaut** [comment]
Thank you!
