### PR TITLE
Specialize `formatter` for all `std::basic_string` types

### LINKED ISSUE #3938: Formatting for strings with custom allocators fails to compile
When using a `std::basic_string` with a custom allocator, it fails to compile in a few use cases, e.g.:

```cpp
std::string f1() {
    // This compiles.
    return fmt::format("{}", std::tuple<std::string>{});
}

std::string f2() {
    // This compiles.
    return fmt::format("{}", std::pmr::string{});
}

std::string f3() {
    // This does not compile.
    return fmt::format("{}", std::tuple<std::pmr::string>{});
}
```

You can reproduce the error here: https://godbolt.org/z/4oa1jqr1G

I checked the code, and it seems `std::basic_string` is specialized only for the default allocator. I think the fix might be as simple as replacing

```cpp
FMT_FORMAT_AS(std::basic_string<Char>, basic_string_view<Char>);
```

with

```cpp
template <typename Char, typename Alloc>
class formatter<std::basic_string<Char, std::char_traits<Char>, Alloc>, Char>
    : public formatter<basic_string_view<Char>, Char> {};
```

It is also not clear why printing a `std::pmr::string` alone works. Maybe it's falling back to `string_view` while the tuple version is not.

### PR DESCRIPTION
**Pull request by dieram3**
This fixes #3938 by adding a `formatter` partial specialization that covers all `std::basic_string` types, such as `std::pmr::string`.

Additionally, this adds the old-school allocator member types to `mock_allocator` in order to make GCC 4.8 happy. If GCC 4.8 support is removed in the future, these member types can be removed as they are the defaults of `allocator_traits`.

### CODE REVIEW

File: test/format-test.cc [hunk 1]
```diff
@@ -2222,16 +2223,21 @@ template <typename Char, typename... T> void check_enabled_formatters() {
...
                            unsigned short, int, unsigned, long, unsigned long,
                            long long, unsigned long long, float, double,
                            long double, void*, const void*, char*, const char*,
-                           std::string, std::nullptr_t>();
-  check_enabled_formatters<wchar_t, bool, wchar_t, signed char, unsigned char,
-                           short, unsigned short, int, unsigned, long,
-                           unsigned long, long long, unsigned long long, float,
-                           double, long double, void*, const void*, wchar_t*,
-                           const wchar_t*, std::wstring, std::nullptr_t>();
+                           std::string, custom_string, std::nullptr_t>();
```
Comment (dieram3) [inline test/format-test.cc:2235]: This is my best guess on where this code change should be tested. I figured that given we already test the `std::string` specialization at runtime, testing only the compilation of `custom_string` might be enough.

File: include/fmt/format.h [hunk 2]
```diff
@@ -4017,11 +4017,14 @@ FMT_FORMAT_AS(unsigned short, unsigned);
 FMT_FORMAT_AS(long, detail::long_type);
 FMT_FORMAT_AS(unsigned long, detail::ulong_type);
 FMT_FORMAT_AS(Char*, const Char*);
-FMT_FORMAT_AS(std::basic_string<Char>, basic_string_view<Char>);
 FMT_FORMAT_AS(std::nullptr_t, const void*);
 FMT_FORMAT_AS(detail::std_string_view<Char>, basic_string_view<Char>);
 FMT_FORMAT_AS(void*, const void*);
 
+template <typename Char, typename Traits, typename Allocator>
+class formatter<std::basic_string<Char, Traits, Allocator>, Char>
```
[the remark this answers is not in the document]
Comment (vitaut) [reply include/fmt/format.h:4025]: Yes, `Traits` should be ignored and I agree that it's better to handle string_view separately.

File: test/format-test.cc (hunk 1 above)
Comment (vitaut) [reply test/format-test.cc:2235]: Looks OK but you need to add `rebind` to `mock_allocator` to fix https://github.com/fmtlib/fmt/actions/runs/8779818010/job/24107542630?pr=3943.

**Review by vitaut — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: test/format-test.cc (hunk 1 above)
Comment (dieram3) [reply test/format-test.cc:2235]: Yikes, GCC 4.8.

Added the required member types and validated here: https://godbolt.org/z/a1o7YjY5M (every single one of them is required).
I also updated the PR description accordingly (in case you use it as the commit message).

If you don't plan to support GCC 4.8 much longer (which is 11 years old), it might make sense to add a note to remove these types later.

**Review by vitaut — APPROVED** [review]

File: test/format-test.cc (hunk 1 above)
Comment (vitaut) [reply test/format-test.cc:2235]: Thanks. There are no plans to drop gcc 4.8 at the moment.
