### PR TITLE
Make colored print handle UTF-8

### LINKED ISSUE #2681: UTF8 doesn't work with text styles
I'm using vs2022 and have set `/utf-8` option.
Thr example code 
`fmt::print(
  "┌{0:─^{2}}┐\n"
  "│{1: ^{2}}│\n"
  "└{0:─^{2}}┘\n", "", "Hello, world!", 20);`
works fine.
But when I try to add some text style,
`fmt::print(fmt::fg(fmt::color::red),
  "┌{0:─^{2}}┐\n"
  "│{1: ^{2}}│\n"
  "└{0:─^{2}}┘\n", "", "Hello, world!", 20);`
the output get garbled.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fixes #2681 

The working flow:
 * With `is_utf8()` calls `detail::print` that specifically converts to UTF-16 and calls `WriteConsoleW` 
 * Without `is_utf8()` calls `fwrite_fully`

The broken flow:
 * Always call `fputs`

The fix:
 * With `is_utf8()` call `detail::print` 
 * Without `is_utf8()` keep calling `fputs`, as `fwrite_fully` is not exported

This is tested on Windows only. On Windows `fputs` does not do any magic, and color sequences are processed by `WriteConsole`. I'm not sure if on other platform `fputs` processes these ANSI escape sequences, or `fwrite` will also do.

### CODE REVIEW

**Comment by AlexGuteniev** [comment]
I actually observe inconsistency that non-colored format throws I/O errors but colored directly calls `fputs` without checking. I'm not creating the issue yet, maybe it should be fixed within this change.

File: include/fmt/color.h [hunk 1]
```diff
@@ -529,8 +529,12 @@ void vprint(std::FILE* f, const text_style& ts, const S& format,
             basic_format_args<buffer_context<type_identity_t<Char>>> args) {
   basic_memory_buffer<Char> buf;
   detail::vformat_to(buf, ts, to_string_view(format), args);
-  buf.push_back(Char(0));
-  detail::fputs(buf.data(), f);
+  if (detail::is_utf8())
+    detail::print(f, basic_string_view<Char>(buf.begin(), buf.size()));
```
Comment (vitaut) [inline include/fmt/color.h:533]: Please wrap the body of the if statement in curly braces since else is braced.

**Review by vitaut — CHANGES_REQUESTED** [review]
Thanks for the PR!

> I actually observe inconsistency that non-colored format throws I/O errors but colored directly calls fputs without checking. I'm not creating the issue yet, maybe it should be fixed within this change.

Good catch, please add an error check here or in a separate PR.

**Review by vitaut — APPROVED** [review]
