### PR TITLE
Fix range suppresor formatter

### LINKED ISSUE #4123: Cannot suppress range formatter when type has a container_type member type.
The enabling condition of the adaptor formatter around line 838 of ranges.h is:

    enable_if_t<conjunction<detail::is_container_adaptor_like<T>,
                            bool_constant<range_format_kind<T, Char>::value ==
                                          range_format::disabled>>::value>>

This is probably supposed to be:

    enable_if_t<conjunction<detail::is_container_adaptor_like<T>,
                            bool_constant<range_format_kind<T, Char>::value !=
                                          range_format::disabled>>::value>>

So that the formatter may be disabled via a is_range specialization.

See compilation error in https://godbolt.org/z/Kq33exr6x

### PR DESCRIPTION
**Pull request by soumik15630m**
Fixes #4123.

### Problem
The `formatter` specialization for container adaptors (like `std::stack`, `std::queue`, `std::priority_queue`) was overly aggressive. It matched any type with a `container_type` member alias, causing ambiguous partial specializations when someone tried to define a custom formatter for their own types that happened to have a `container_type`.

### Solution
added a `fmt::is_container_adaptor<T>` trait. This defaults to `std::true_type` but allows users to specialize it to `std::false_type` for their custom types. This removes the library's adaptor formatter from the overload set via SFINAE, resolving the ambiguity and allowing custom formatters to work.

### Verification
Added a regression test in `test/ranges-test.cc` (`container_adaptor_partial_specialization`) to test the fix and all 

thanks .. please let me know if anything need to be changed

### CODE REVIEW

**Comment by soumik15630m** [comment]
@vitaut Tried to fix the problem, check once and please let me know if I need to update anything 
Thanks ..

**Comment by soumik15630m** [comment]
Ping! 
Friendly ping — this PR has all ci  checks passed.
Let me know if there’s anything else needed.
Thanks 👍

**Comment by soumik15630m** [comment]
> Thanks for the PR! I don't think we should introduce another trait for this. Have you tried applying the suggestion from https://github.com/fmtlib/fmt/issues/4123#issue-2470353471?

I considered the approach from #4123, but it would disable formatting for standard adaptors like std::stack, std::queue, and std::priority_queue.
These types are not ranges and resolve to range_format::disabled, so checking != disabled would incorrectly exclude them. The current == disabled logic is what allows the adaptor formatter to trigger correctly.

I introduced the `is_container_adaptor` trait to distinguish between "standard adaptors (which are disabled ranges)" and "user types that explicit opt-out via `is_range` specialization."

Let me know if I missed something or if you'd like me to proceed differently!

**Comment by vitaut** [comment]
I looked into it in more details and you are absolutely right that we cannot reuse the `is_range` trait here. So it makes sense to introduce `is_container_adaptor`. However, I suggest merging `is_container_adaptor_like` into it.

File: test/ranges-test.cc [hunk 1]
```diff
@@ -17,6 +17,10 @@
 #include <utility>
 #include <vector>
 
+#include "fmt/base.h"
+#include "fmt/ranges.h"
+#include "posix-mock.h"
```
Comment (vitaut) [inline test/ranges-test.cc]: I don't think we need these. `fmt/ranges.h` is included above and is effectively a superset of `fmt/base.h`.

File: test/ranges-test.cc [hunk 2]
```diff
@@ -797,3 +801,39 @@ struct not_range {
...
+    std::vector<T> c = {1, 2, 3};
+
+    typename std::vector<T>::const_iterator begin() const { return c.begin(); }
+    typename std::vector<T>::const_iterator end() const { return c.end(); }
+  };
+}  // namespace test_detail
+
+namespace fmt {
+  template <typename T>
+  struct is_range<test_detail::partial_opt_out_wrapper<T>, char> : std::false_type {};
```
Comment (vitaut) [inline test/ranges-test.cc]: I think we should drop this and test that `is_container_adaptor` is sufficient for the opt out.

**Comment by soumik15630m** [comment]
Makes sense. I’ll drop this specialization and use is_container_adaptor for the opt-out. I’ll update the tests accordingly and push the changes.

**Comment by soumik15630m** [comment]
Updated ....
Let me know if there's anything else...

File: include/fmt/ranges.h [hunk 3]
```diff
@@ -347,6 +347,11 @@ template <typename T, typename Char> struct is_range {
       detail::is_range_<T>::value && !detail::has_to_string_view<T>::value;
 };
 
+/**
+ * returns "true" if "T" is a container adaptor (like "std::stack")
+ * that should be formatted by iterating over the underlying container.
+ * */
```
Comment (vitaut) [inline include/fmt/ranges.h]: This needs to be moved to the definition of is_container_adaptor.

**Review by vitaut — CHANGES_REQUESTED** [review]

File: include/fmt/ranges.h (hunk 3 above)
Comment (soumik15630m) [reply include/fmt/ranges.h]: Sure .... it's updated now 

My bad i overlooked it 
thanks

**Comment by vitaut** [comment]
Merged, thank you!

**Comment by soumik15630m** [comment]
Thanks 👍
