### PR TITLE
Fix testsuite on MinGW + MSVCRT

### LINKED ISSUE #2952: Failing tests on MSYS2/MinGW x64
Hello, these are some test failures of a clean build of `fmt` under MSYS2/MinGW x64 on Windows 10 x64. Not sure what's going on here, I will investigate further -- for now I'm capturing the test output for awareness.

---

`chrono-test`: 

```
C:/msys64/home/vromeo5/fmt/test/chrono-test.cc:132: Failure
Expected equality of these values:
  system_strftime(iso_week_spec, &tm)
    Which is: "1975-12-29:   "
  fmt::format(fmt::runtime(fmt_spec), tm)
    Which is: "1975-12-29: 1976 76 01"
C:/msys64/home/vromeo5/fmt/test/chrono-test.cc:132: Failure
Expected equality of these values:
  system_strftime(iso_week_spec, &tm)
    Which is: "1977-01-02:   "
  fmt::format(fmt::runtime(fmt_spec), tm)
    Which is: "1977-01-02: 1976 76 53"

...
```

---

`format-test`:

```
...

←[0;32m[ RUN      ] ←[mformat_test.to_string

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff7ae1eb756 in __netf2 ()
```

---

`format-impl-test`:

```
...

←[0;32m[ RUN      ] ←[mformat_impl_test.write_float128

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff7916b7696 in __netf2 ()
```

---

`xchar-test`:

```
C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:295: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, t1)
    Which is: L"\n"
With diff:
@@ -1,1 +1,2 @@
-L""
+L"
+"

warning: C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:295: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, t1)
    Which is: L"\n"
With diff:
@@ -1,1 +1,2 @@
-L""
+L"
+"
warning:
C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:296: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, tm)
    Which is: L"\n"
With diff:
@@ -1,1 +1,2 @@
-L""
+L"
+"

warning: C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:296: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, tm)
    Which is: L"\n"
With diff:
@@ -1,1 +1,2 @@
-L""
+L"
+"
warning:
warning: Invalid parameter passed to C runtime function.
C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:295: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, t1)
    Which is: L"\t"
warning: C:/msys64/home/vromeo5/fmt/test/xchar-test.cc:295: Failure
Expected equality of these values:
  sys_output
    Which is: L""
  fmt::format(fmt_spec, t1)
    Which is: L"\t"
```

### PR DESCRIPTION
**Pull request by dimztimz**
Fixes #2952. The testsuite indirectly called `strftime()` with conversion specifiers defined only in C99. In MSVCRT this function conforms only to C89. Only in the updated UCRT this functon provides the functionality of C99.

### CODE REVIEW

File: test/chrono-test.cc [hunk 1]
```diff
@@ -121,6 +121,11 @@ TEST(chrono_test, format_tm) {
       make_tm(2000, 1, 2, 12, 14, 16),    // W52
       make_tm(2000, 1, 3, 12, 14, 16)     // W1
   };
+
+#if defined(__MINGW32__) && !defined(_UCRT)
+  GTEST_SKIP();
```
Comment (vitaut) [inline test/chrono-test.cc:126]: Could you add a comment clarifying why we skip this test?

**Review by vitaut — COMMENTED** [review]
Thanks for the PR!

File: test/chrono-test.cc (hunk 1 above)
Comment (dimztimz) [reply test/chrono-test.cc]: Done,

**Comment by vitaut** [comment]
Merged, thanks!
