### PR TITLE
Exclude std::abort from compilation when compiling CUDA with Clang

### LINKED ISSUE #1659: std::abort causes error when compiling CUDA with Clang in device code
Compiling with Clang 9 in CUDA mode results in the following compilation errors during its device code pass:
```cpp
.../fmt-master/include/fmt/format-inl.h:50:8: error: expected identifier
  std::abort();
       ^
.../fmt-master/include/fmt/format-inl.h:50:3: error: unexpected namespace name 'std': expected expression
  std::abort();
  ^
```
One possible fix is to use ```std::terminate``` instead:
```cpp
FMT_FUNC void assert_fail(const char* file, int line, const char* message) {
  print(stderr, "{}:{}: assertion failed: {}", file, line, message);
#if defined(__clang__) && defined(__CUDA__) && defined(__CUDA_ARCH__)
  std::terminate();
#else
  std::abort();
#endif
}
```

### PR DESCRIPTION
**Pull request by invexed**
Excludes ```std::abort``` for device code only. Fixes #1659.

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

File: include/fmt/format-inl.h [hunk 1]
```diff
@@ -47,7 +48,11 @@ namespace internal {
 
 FMT_FUNC void assert_fail(const char* file, int line, const char* message) {
   print(stderr, "{}:{}: assertion failed: {}", file, line, message);
+#if defined(__clang__) && defined(__CUDA__) && defined(__CUDA_ARCH__)
+  std::terminate();
```
Comment (vitaut) [inline include/fmt/format-inl.h:52]: I think we can use `std::terminate` unconditionally but please add a short comment clarifying that it was chosen instead of `abort` because of CUDA.

File: include/fmt/format-inl.h [hunk 2]
```diff
@@ -48,10 +48,9 @@ namespace internal {
 
 FMT_FUNC void assert_fail(const char* file, int line, const char* message) {
   print(stderr, "{}:{}: assertion failed: {}", file, line, message);
-#if defined(__clang__) && defined(__CUDA__) && defined(__CUDA_ARCH__)
+  // Chosen instead of std::abort to satisfy Clang in CUDA mode during device
+  // code pass.
   std::terminate();
-#else
-  std::abort();
 #endif
```
Comment (vitaut) [inline include/fmt/format-inl.h:54]: Extra `#endif`.

Comment (invexed) [reply include/fmt/format-inl.h]: My bad. I Tested the wrong branch locally!

**Comment by vitaut** [comment]
Thanks!
