### PR TITLE
Fix negative subsec for time_point

### LINKED ISSUE #3117: Formatting std::chrono::time_point with double Rep or before Epoch
Hi,

I have two questions concerning formatting the `time_point` object with `fmt`:

1. It seems that it cannot format `time_point` with `Rep` set to `double`, could this be improved?
2. It seems that it incorrectly formats timepoint before Epoch, you can see negative sub-seconds number in the output.

Compiler Explorer: https://godbolt.org/z/qd4Y3b7P9

Code:

```c++
#include <fmt/format.h>
#include <fmt/chrono.h>
#include <fmt/ostream.h>

template <typename Dur>
std::string getTimestamp(const std::chrono::time_point<std::chrono::system_clock, Dur>& tp)
{
    using namespace std::chrono;
    const auto tp_ms = time_point_cast<milliseconds>(tp);
    const auto milli_count = (tp_ms.time_since_epoch()).count() % 1000;
    return fmt::format("{:%Y-%m-%d_%H:%M:%S}.{:03d}", tp_ms, milli_count);
}

template <typename Dur>
std::string getTimestamp2(const std::chrono::time_point<std::chrono::system_clock, Dur>& tp)
{
    using namespace std::chrono;
    const auto milli_count = duration_cast<milliseconds>(tp.time_since_epoch()).count() % 1000;
    return fmt::format("{:%Y-%m-%d_%H:%M:%S}.{:03d}", tp, milli_count); // Passing tp to format directly
}

std::chrono::system_clock::time_point makeTimePoint(const std::tm& tm1, double fraction)
{
    struct std::tm tm2 = tm1;
    const auto t = std::mktime(&tm2);

    using namespace std::chrono;
    constexpr auto DEN = system_clock::duration::period::den;
    const auto count_subsecs = static_cast<system_clock::rep>(t) * DEN +
                               static_cast<system_clock::rep>(fraction * DEN);
    system_clock::time_point tp(system_clock::duration{count_subsecs});
    return tp;
}

int main()
{
    const auto tp = std::chrono::system_clock::now();
    const auto tp2 = std::chrono::time_point_cast<std::chrono::duration<double>>(tp);

    fmt::print("timepoint: {}\n", getTimestamp(tp));
    fmt::print("timepoint: {}\n", getTimestamp(tp2));

    // Issue 1:
    // fmt::print("timepoint: {}\n", getTimestamp2(tp2)); // This causes build error at line 19 above.

    // Issue 2:
    std::tm tm{};
    tm.tm_year = 1969 - 1900;
    tm.tm_mon = 12 - 1;
    tm.tm_mday = 31;
    tm.tm_hour = 23;
    tm.tm_min = 59;
    tm.tm_sec = 59;
    const auto tp3 = makeTimePoint(tm, 0.123456);
    fmt::print("timepoint: {}\n", getTimestamp(tp3)); // timepoint: 1970-01-01_00:00:00.-876
}
```

### PR DESCRIPTION
**Pull request by ShawnZhong**
Fix #3117

The following piece of code (https://godbolt.org/z/4qr5389ns) used to print `59.000 00.750 00.500 00.250 00.000 00.250 00.500 00.750 01.000`, which is wrong. After this PR, it now correctly prints `59.000 59.250 59.500 59.750 00.000 00.250 00.500 00.750 01.000`

```cpp
const auto epoch = std::chrono::time_point<std::chrono::system_clock,
                                           std::chrono::milliseconds>();
const auto d = std::chrono::milliseconds(250);
for (int i = -4; i <= 4; i++) {
  fmt::print("{:%S} ", epoch + i * d);
}
```

### CODE REVIEW

File: include/fmt/chrono.h [hunk 1]
```diff
@@ -2127,9 +2107,15 @@ struct formatter<std::chrono::time_point<std::chrono::system_clock, Duration>,
...
-      const auto subsecs = std::chrono::duration_cast<Duration>(
+      auto subsecs = std::chrono::duration_cast<Duration>(
           epoch - std::chrono::duration_cast<std::chrono::seconds>(epoch));
 
+      if (subsecs.count() < 0) {
+        subsecs += std::chrono::seconds(1);
+        val -= std::chrono::seconds(1);
+      }
+
+
```
Comment (vitaut) [inline include/fmt/chrono.h:2118]: nit: extra newline

File: test/chrono-test.cc [hunk 2]
```diff
@@ -879,4 +879,20 @@ TEST(chrono_test, timestamps_sub_seconds) {
...
+
+  {
+    const auto epoch = std::chrono::time_point<std::chrono::system_clock,
+                                               std::chrono::milliseconds>();
+    const auto d = std::chrono::milliseconds(250);
+
+    EXPECT_EQ("59.000", fmt::format("{:%S}", epoch - 4 * d));
+    EXPECT_EQ("59.250", fmt::format("{:%S}", epoch - 3 * d));
+    EXPECT_EQ("59.500", fmt::format("{:%S}", epoch - 2 * d));
+    EXPECT_EQ("59.750", fmt::format("{:%S}", epoch - 1 * d));
```
Comment (vitaut) [inline test/chrono-test.cc:891]: I'm not sure if we need all four of these checks because they are effectively testing the same thing. One is probably enough.

File: test/chrono-test.cc [hunk 3]
```diff
@@ -879,4 +879,20 @@ TEST(chrono_test, timestamps_sub_seconds) {
...
+    EXPECT_EQ("00.000", fmt::format("{:%S}", epoch));
+    EXPECT_EQ("00.250", fmt::format("{:%S}", epoch + 1 * d));
+    EXPECT_EQ("00.500", fmt::format("{:%S}", epoch + 2 * d));
+    EXPECT_EQ("00.750", fmt::format("{:%S}", epoch + 3 * d));
+    EXPECT_EQ("01.000", fmt::format("{:%S}", epoch + 4 * d));
```
Comment (vitaut) [inline test/chrono-test.cc:896]: Same here.

**Review by vitaut — COMMENTED** [review]
Thanks for the PR! Overall looks good, just some minor comments inline.

**Comment by vitaut** [comment]
Thank you!

**Comment by vitaut** [comment]
This change triggers a ubsan error on the following case:

```c++
#include <fmt/chrono.h>

int main() {
  auto d = std::chrono::system_clock::duration(-9223372036854767584);
  fmt::print("{:}", std::chrono::system_clock::time_point(d));
}
```

```
.../chrono:1111:111: runtime error: signed integer overflow: -9223372036854767584 - 1000000 cannot be represented in type 'long long'
```

Stack trace:

```
  * frame #0: 0x000000010037ea20 libclang_rt.ubsan_osx_dynamic.dylib`__ubsan_handle_sub_overflow
    frame #1: 0x000000010000b5bd a.out`std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>::operator-=(this=0x00007ff7bfefd190, __d=0x00007ff7bfefd140) at chrono:1111:111
    frame #2: 0x000000010000a835 a.out`std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>::operator-=(this=0x00007ff7bfefd190, __d=0x00007ff7bfefd140) at chrono:1390:111
    frame #3: 0x0000000100005b18 a.out`decltype(fp0.out()) fmt::v9::formatter<std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, char, void>::format<fmt::v9::basic_format_context<fmt::v9::appender, char>>(this=0x00007ff7bfefd1f0, val=time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000> > > @ 0x00007ff7bfefd190, ctx=0x00007ff7bfefef40) const at chrono.h:2113:13
    frame #4: 0x0000000100005802 a.out`void fmt::v9::detail::value<fmt::v9::basic_format_context<fmt::v9::appender, char>>::format_custom_arg<std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, fmt::v9::formatter<std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, char, void>>(arg=0x00007ff7bfeff4c8, parse_ctx=0x00007ff7bfefef28, ctx=0x00007ff7bfefef40) at core.h:1332:22
    frame #5: 0x000000010006a839 a.out`fmt::v9::basic_format_arg<fmt::v9::basic_format_context<fmt::v9::appender, char>>::handle::format(this=0x00007ff7bfefd2e0, parse_ctx=0x00007ff7bfefef28, ctx=0x00007ff7bfefef40) const at core.h:1595:7
    frame #6: 0x0000000100079db8 a.out`fmt::v9::detail::custom_formatter<char>::operator()(this=0x00007ff7bfefdb70, h=handle @ 0x00007ff7bfefd2e0) const at format.h:3603:7
    frame #7: 0x000000010006f4ca a.out`void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::detail::vformat_args<char>::type, fmt::v9::detail::locale_ref)::format_handler::on_format_specs(int, char const*, char const*) [inlined] decltype(fp(0)) fmt::v9::visit_format_arg<fmt::v9::detail::custom_formatter<char>, fmt::v9::basic_format_context<fmt::v9::appender, char>>(vis=0x00007ff7bfefdb70, arg=0x00007ff7bfefe2f0) at core.h:1659:12
    frame #8: 0x000000010006e35d a.out`void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::detail::vformat_args<char>::type, fmt::v9::detail::locale_ref)::format_handler::on_format_specs(this=0x00007ff7bfefef28, id=0, begin="}", end="") at format.h:4205:9
    frame #9: 0x000000010006d9b7 a.out`char const* fmt::v9::detail::parse_replacement_field<char, void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::detail::vformat_args<char>::type, fmt::v9::detail::locale_ref)::format_handler&>(begin=":}", end="", handler=0x00007ff7bfefef28) at core.h:2558:23
    frame #10: 0x000000010002e93c a.out`void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::detail::vformat_args<char>::type, fmt::v9::detail::locale_ref) at core.h:2583:21
    frame #11: 0x000000010002e674 a.out`void fmt::v9::detail::vformat_to<char>(buf=0x00007ff7bfeff1e0, fmt=(data_ = "{:}", size_ = 3), args=fmt::v9::detail::vformat_args<char>::type @ 0x00007ff7bfefefb8, loc=(locale_ = 0x0000000000000000)) at format.h:4221:3
    frame #12: 0x000000010002f44c a.out`fmt::v9::vprint(f=0x00007ff858747c98, format_str=(data_ = "{:}", size_ = 3), args=fmt::v9::format_args @ 0x00007ff7bfeff1b0) at format-inl.h:1531:3
    frame #13: 0x000000010002f6af a.out`fmt::v9::vprint(format_str=(data_ = "{:}", size_ = 3), args=fmt::v9::format_args @ 0x00007ff7bfeff430) at format-inl.h:1547:3
    frame #14: 0x0000000100004325 a.out`main [inlined] void fmt::v9::print<std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>>(fmt=fmt::v9::format_string<std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000> > > > @ 0x00007ff7bfeff578, args=0x00007ff7bfeff4c8) at core.h:2983:30
    frame #15: 0x000000010000406d a.out`main at test.cc:5:3
```

**Comment by ShawnZhong** [comment]
I attempted to resolve this ub by first converting the `time_point` to use a rep of `seconds`, and then substract 1 second it. However, I encountered an ub when converting a `time_point` representing -9223372036855 seconds before epoch to a `time_t` (, which should contain the same value for almost all platforms).

```cpp
#include <fmt/chrono.h>

int main() {
  auto val = -9223372036854767584 / 1'000'000 - 1;  // -9223372036855
  auto tp =
      std::chrono::time_point<std::chrono::system_clock, std::chrono::seconds>(
          std::chrono::seconds(val));
  auto time = std::chrono::system_clock::to_time_t(tp);
  fmt::print("{} {}", val, time);  
  // expected: -9223372036855 -9223372036855
  // actual:   -9223372036855 9223372036854
}
```

The message from the sanitizer is as follows:

```
/opt/homebrew/opt/llvm/bin/../include/c++/v1/__chrono/duration.h:97:59: runtime error: signed integer overflow: -9223372036855 * 1000000 cannot be represented in type 'long long'
    #0 0x1007d12a8 in std::__1::chrono::__duration_cast<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, std::__1::ratio<1000000l, 1l>, false, true>::operator()[abi:v15006](std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&) const duration.h:97
    #1 0x1007d1174 in std::__1::enable_if<__is_duration<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::value, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::type std::__1::chrono::duration_cast[abi:v15006]<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, long long, std::__1::ratio<1l, 1l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&) duration.h:124
    #2 0x1007d10e8 in std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >::duration[abi:v15006]<long long, std::__1::ratio<1l, 1l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&, std::__1::enable_if<(__no_overflow<std::__1::ratio<1l, 1l>, std::__1::ratio<1l, 1000000l> >::value) && ((std::__1::integral_constant<bool, false>::value) || (((__no_overflow<std::__1::ratio<1l, 1l>, std::__1::ratio<1l, 1000000l> >::type::den) == (1)) && (!(treat_as_floating_point<long long>::value)))), void>::type*) duration.h:271
    #3 0x1007d1020 in std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >::duration[abi:v15006]<long long, std::__1::ratio<1l, 1l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&, std::__1::enable_if<(__no_overflow<std::__1::ratio<1l, 1l>, std::__1::ratio<1l, 1000000l> >::value) && ((std::__1::integral_constant<bool, false>::value) || (((__no_overflow<std::__1::ratio<1l, 1l>, std::__1::ratio<1l, 1000000l> >::type::den) == (1)) && (!(treat_as_floating_point<long long>::value)))), void>::type*) duration.h:271
    #4 0x1007d0f24 in std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::time_point[abi:v15006]<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > > const&, std::__1::enable_if<is_convertible<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::value, void>::type*) time_point.h:55
    #5 0x1007d0d54 in std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::time_point[abi:v15006]<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > > const&, std::__1::enable_if<is_convertible<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::value, void>::type*) time_point.h:55
    #6 0x1007d0670 in main main.cpp:9
    #7 0x1a6487e4c  (<unknown module>)
    #8 0x8a3c7ffffffffffc  (<unknown module>)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opt/homebrew/opt/llvm/bin/../include/c++/v1/__chrono/duration.h:97:59
````

I don't know why the library would multiply the seconds by 1,000,000 and then convert it to `time_t` (which again divides by 1,000,000).

**Comment by vitaut** [comment]
I turned the UB into an error in https://github.com/fmtlib/fmt/commit/240b728d813b52a9b616b1060f8fb52837ddb0c1. If you have a better idea, a PR would be welcome.
